import { getTodos } from "@/redux/appRedux/action";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import {BsSearch} from "react-icons/bs"
import {useDispatch,useSelector} from "react-redux"


export async function getServerSideProps({ req, res, params, query }) {
  // code

  return {
    props: {},
  }
}


export default function Home() {
  const dispatch=useDispatch()
  const todos=useSelector((state)=>state.appReducer.todos)

  useEffect(() => {
    dispatch(getTodos())
  },[])
  
  return (
    <>
      <Head>
        <title>MyNotes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*Start of  Filter and Sort Wrapper Box*/}

        <div className="flex items-center box-border pl-[20px] w-[90%] m-auto mt-[30px] justify-between ">
          {/*Search Wrapper Box*/}
          <div className="w-[40%] border-[1px] flex items-center gap-[10px] pr-[15px] px-[10px] pt-[8px] pb-[8px] rounded-[5px]">
            <input type="text"  className="border-none outline-none w-[100%] text-[17px]"/>
            <span><BsSearch className="text-[25px] text-slate-500"/></span>
          </div>
          {/*Calender and Select Wrapper Box*/}
          <div className=' flex align-center gap-[50px] '>
            {/*Calender Wrapper Box*/}

            <div>
              <input
                type="date"
                className="outline-none border-[1px] rounded-[5px] p-[8px] pt-[5px] pb-[5px]"
              />
            </div>
            {/*Select Wrapper Box*/}
           
              <select className="border-[1px] p-[5px] outline-none">
                <option value="">Select</option>
                <option value="latest">Recent</option>
                <option value="oldest">Older</option>
              </select>
           
          </div>
        </div>
        {/*End of Filter and Sort Wrapper Box*/}

       <div>
        <ul className="text-center">
        {  todos && todos.map((ele,index)=>{
            return <li key={index}>
              {ele.todo}
            </li>
          })}
        </ul>
       </div>
      </main>
    </>
  );
}
