import getNotes from "@/helper/calls";
import Head from "next/head";
import {BsSearch} from "react-icons/bs"
import AllNotes from "./api/notes/user/notes/all";


export async function getServerSideProps({ req, res, params, query }) {
   const notes=await getNotes()
  return {
    props: {notes},
  }
}


export default function Home({notes}) {

  return (
    <>
      <Head>
        <title>MyNotes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/*Start of  Filter and Sort Wrapper Box*/}

        <div className="flex items-center box-border pl-[20px] w-[90%] m-auto mt-[30px] justify-between ">
          {/*Search Wrapper Box*/}
          <div className="w-[40%] border-[1px] flex items-center gap-[10px] pr-[15px] px-[10px] pt-[8px] pb-[8px] rounded-[5px]">
            <input type="text"  className="border-none outline-none w-[100%] text-[17px]"/>
            <span><BsSearch className="text-[25px] text-slate-500"/></span>
          </div>
          {/*Calender and Select Wrapper Box*/}
          <div className=' flex align-center gap-[50px] '>
            {/*Calender Wrapper Box*/}

            <div>
              <input
                type="date"
                className="outline-none border-[1px] rounded-[5px] p-[8px] pt-[5px] pb-[5px]"
              />
            </div>
            {/*Select Wrapper Box*/}
           
              <select className="border-[1px] p-[5px] outline-none">
                <option value="">Select</option>
                <option value="latest">Recent</option>
                <option value="oldest">Older</option>
              </select>
           
          </div>
        </div>
          {
            notes && notes.map((ele)=>
              <AllNotes key={ele._id} notes={ele} />
            )
          }
      </main>
    </>
  );
}
